Repository rhfrhftkxtkx/theDay-thePlace, pull requests merged in 2025-09, with the labels that each got.

#13 Feat: Detail Page Layout 및 국가 유산 detail page
  src/components/DetailPageLayout.svelte
  src/components/ui/FallbackImage.svelte
  src/components/ui/ResultCard.svelte
  src/components/ui/TextCollapse.svelte
  src/lib/components/ui/tabs/index.ts
  src/lib/components/ui/tabs/tabs-content.svelte
  src/lib/components/ui/tabs/tabs-list.svelte
  src/lib/components/ui/tabs/tabs-trigger.svelte
  src/lib/components/ui/tabs/tabs.svelte
  src/routes/(details)/ccba/+page.server.ts
  src/routes/(details)/ccba/+page.svelte
  src/routes/(details)/museum/+page.svelte
  src/types/detail.types.ts
Labels: enhancement

#18 fix/map: 지도 줌에 따라 마커 표시 여부 기능 추가, 변수명 정리, 주석 추가
  src/routes/+page.svelte
  src/routes/+page.ts
  src/routes/api/detail/[contentid]/+server.ts
Labels: enhancement

#21 Fix/search
  src/routes/(search)/api/search/ccbaSearch.ts
  src/routes/(search)/api/search/museumSearch.ts
Labels: bug

#23 Feat/login page
  package-lock.json
  package.json
  src/app.d.ts
  src/components/features/SideMenu.svelte
  src/hooks.server.ts
  src/lib/mapTypes.ts
  src/lib/server/supabase.ts
  src/lib/supabaseClient.ts
  src/routes/(login&signup)/login/+page.server.ts
  src/routes/(login&signup)/login/+page.svelte
  src/routes/(login&signup)/login/+page.ts
  src/routes/(login&signup)/logout/+page.server.ts
  src/routes/(login&signup)/signup/+page.server.ts
  src/routes/(login&signup)/signup/+page.svelte
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+page.server.ts
  src/routes/+page.svelte
  src/routes/+page.ts
Labels: enhancement

#28 Fix/sideMenu
  src/components/features/SideMenu.svelte
  src/routes/(login&signup)/login/+page.ts
  src/routes/+layout.svelte
  src/routes/+page.server.ts
  src/routes/+page.svelte
  src/routes/favorites/+page.server.ts
  src/routes/favorites/+page.svelte
Labels: enhancement

#29 서버 응답통합 및 env 재수정
  src/app.d.ts
  src/components/ResultList.svelte
  src/components/ui/ResultCard.svelte
  src/hooks.server.ts
  src/lib/server/supabase.ts
  src/lib/supabaseClient.ts
  src/routes/(search)/api/search/+server.ts
  src/routes/(search)/common/+page.svelte
  src/stores/store.ts
  src/types/search.types.ts
Labels: enhancement

#30 Fix: 아이폰에서 레이아웃이 깨지던 문제 해결
  package-lock.json
  package.json
  postcss.config.js
  src/hooks.server.ts
  src/lib/components/ui/carousel/carousel-content.svelte
  src/routes/(details)/museum/+page.server.ts
  src/routes/(details)/museum/+page.svelte
Labels: bug, Resolved

#32 Feat : 즐겨찾기
  src/components/ui/TextCollapse.svelte
  src/lib/components/ui/HeartIcon.svelte
  src/routes/+layout.server.ts
  src/routes/+page.server.ts
  src/routes/+page.svelte
  src/routes/+page.ts
  src/routes/favorites/+page.server.ts
  src/routes/favorites/+page.svelte
Labels: enhancement

#33 refactor: 상세검색에도 즐겨찾기 추가
  src/routes/(details)/museum/+page.server.ts
  src/routes/(details)/museum/+page.svelte
Labels: enhancement

#37 Feat: 유적지 및 문화유산 표기
  src/lib/mapTypes.ts
  src/routes/(search)/api/search/ccbaOverview/+server.ts
  src/routes/(search)/api/search/ccbaSearch.ts
  src/routes/+page.svelte
Labels: bug, enhancement
